
name: Deploy to Turtle & Dove
on: push

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    container: alpine
    timeout-minutes: 5
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: "turtle.science.uu.nl,dove.science.uu.nl"
        port: 22
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd /srv/TrustSECO-DLT

          git pull

          # This loads NVM
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          nvm use
          npm install

          sudo systemctl restart TrustSECO-DLT
